/* generated by pull.js */
const manifest = {
    "name": "Multi Sprite Selecting",
    "description": "Adds a checkbox that, when checked, adds Select All, Unselect All, Delete and Export Selected Sprites Buttons. You can select each sprite by clicking on it's sprite box.",
    "editorOnly": true,
    // "noTranslations": true,
    "info": [
        {
          "text": "When the 'Select Sprites' checkbox is checked, the delete button of each sprite, the stage and the stage size toggle buttons are hidden until it's unchecked.",
          "id": "checkbox-notice"
        }
    ],
    "credits": [
        {
            "name": "MrIncredibleMaker",
            "link": "https://scratch.mit.edu/users/MrIncredibleMakerZe/"
        }
    ],
    "userscripts": [
        {
            "url": "userscript.js"
        }
    ],
    "userstyles": [
        {
          "url": "multi-sprite-selecting.css"
        }
    ],
    "tags": ["recommended", "dinosaurmod", "new"],
    "enabledByDefault": true,
    "dynamicEnable": true,
    "dynamicDisable": false
};
export default manifest;