/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./multi-sprite-selecting.css";
export const resources = {
  "userscript.js": _js,
  "multi-sprite-selecting.css": _css,
};
